In [16]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier 
from sklearn.model_selection import train_test_split

In [11]:
df=pd.read_csv("Churn_Modelling.csv")
df.head(3)

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1

In [12]:
df=df.drop(columns=["RowNumber","CustomerId","Surname"],axis=1)
df.head(2)

CreditScore Geography  Gender  Age  Tenure   Balance  NumOfProducts  \
0          619    France  Female   42       2      0.00              1   
1          608     Spain  Female   41       1  83807.86              1   

   HasCrCard  IsActiveMember  EstimatedSalary  Exited  
0          1               1        101348.88       1  
1          0               1        112542.58       0

In [13]:
df=pd.get_dummies(df,columns=["Geography","Gender"],drop_first=True)

In [14]:
df.head(3)

CreditScore  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0          619   42       2       0.00              1          1   
1          608   41       1   83807.86              1          0   
2          502   42       8  159660.80              3          1   

   IsActiveMember  EstimatedSalary  Exited  Geography_Germany  \
0               1        101348.88       1              False   
1               1        112542.58       0              False   
2               0        113931.57       1              False   

   Geography_Spain  Gender_Male  
0            False        False  
1             True        False  
2            False        False

In [15]:
y=df["Exited"]
x=df.drop(["Exited"],axis=1)

In [18]:
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.7,random_state=61)

In [19]:
rf=RandomForestClassifier()
model=rf.fit(x_train,y_train)
model.score(x_test,y_test)

0.8583333333333333

In [27]:
x=df.sample().drop(["Exited"],axis=1)

In [30]:
model.predict([[712,31,9,0,5,1,1,200000,False,False,True]])

C:\Users\omer_\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


array([1], dtype=int64)

In [36]:
df=pd.DataFrame()

In [37]:
df["takım"]=["BJK","FB","GS","TS","AG","AG","RM","BAR","SS","BDR"]

In [39]:
pd.get_dummies(df,columns=["takım"])

takım_AG  takım_BAR  takım_BDR  takım_BJK  takım_FB  takım_GS  takım_RM  \
0     False      False      False       True     False     False     False   
1     False      False      False      False      True     False     False   
2     False      False      False      False     False      True     False   
3     False      False      False      False     False     False     False   
4      True      False      False      False     False     False     False   
5      True      False      False      False     False     False     False   
6     False      False      False      False     False     False      True   
7     False       True      False      False     False     False     False   
8     False      False      False      False     False     False     False   
9     False      False       True      False     False     False     False   

   takım_SS  takım_TS  
0     False     False  
1     False     False  
2     False     False  
3     False      True  
4     False     False  
5     False     False  
6     False     False  
7     False     False  
8      True     False  
9     False     False

In [40]:
from sklearn.preprocessing import OneHotEncoder #get_dummiesin profesyonel hali

In [46]:
ohe=OneHotEncoder()	
x=ohe.fit_transform(df[["takım"]])

In [47]:
x.toarray()

array([[0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.]])

In [48]:
ohe.transform([["FB"]]).toarray()

C:\Users\omer_\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


array([[0., 0., 0., 0., 1., 0., 0., 0., 0.]])

In [49]:
df=pd.read_csv("Churn_Modelling.csv")
df.head(3)

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1

In [50]:
df=df.drop(columns=["RowNumber","CustomerId","Surname"],axis=1)
df.head(2)

CreditScore Geography  Gender  Age  Tenure   Balance  NumOfProducts  \
0          619    France  Female   42       2      0.00              1   
1          608     Spain  Female   41       1  83807.86              1   

   HasCrCard  IsActiveMember  EstimatedSalary  Exited  
0          1               1        101348.88       1  
1          0               1        112542.58       0

In [52]:
ohe=OneHotEncoder()
xd=ohe.fit_transform(df[["Geography","Gender"]]).toarray()

In [54]:
ohe.get_feature_names_out()

array(['Geography_France', 'Geography_Germany', 'Geography_Spain',
       'Gender_Female', 'Gender_Male'], dtype=object)

In [56]:
xd=pd.DataFrame(xd)
xd.columns=ohe.get_feature_names_out()

In [57]:
xd

Geography_France  Geography_Germany  Geography_Spain  Gender_Female  \
0                  1.0                0.0              0.0            1.0   
1                  0.0                0.0              1.0            1.0   
2                  1.0                0.0              0.0            1.0   
3                  1.0                0.0              0.0            1.0   
4                  0.0                0.0              1.0            1.0   
...                ...                ...              ...            ...   
9995               1.0                0.0              0.0            0.0   
9996               1.0                0.0              0.0            0.0   
9997               1.0                0.0              0.0            1.0   
9998               0.0                1.0              0.0            0.0   
9999               1.0                0.0              0.0            1.0   

      Gender_Male  
0             0.0  
1             0.0  
2             0.0  
3             0.0  
4             0.0  
...           ...  
9995          1.0  
9996          1.0  
9997          0.0  
9998          1.0  
9999          0.0  

[10000 rows x 5 columns]

In [58]:
df=df.drop(columns=["Geography","Gender"])
df.head(3)

CreditScore  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0          619   42       2       0.00              1          1   
1          608   41       1   83807.86              1          0   
2          502   42       8  159660.80              3          1   

   IsActiveMember  EstimatedSalary  Exited  
0               1        101348.88       1  
1               1        112542.58       0  
2               0        113931.57       1

In [59]:
df[xd.columns]=xd

In [60]:
df.head(2)

CreditScore  Age  Tenure   Balance  NumOfProducts  HasCrCard  \
0          619   42       2      0.00              1          1   
1          608   41       1  83807.86              1          0   

   IsActiveMember  EstimatedSalary  Exited  Geography_France  \
0               1        101348.88       1               1.0   
1               1        112542.58       0               0.0   

   Geography_Germany  Geography_Spain  Gender_Female  Gender_Male  
0                0.0              0.0            1.0          0.0  
1                0.0              1.0            1.0          0.0

In [62]:
y=df["Exited"]
x=df.drop(["Exited"],axis=1)

In [63]:
from sklearn.tree import DecisionTreeClassifier

In [64]:
tree=DecisionTreeClassifier()
model=tree.fit(x,y)
model.score(x,y)#overfiting

1.0